### ISSUE TITLE
com.tinify.ConnectionException: Error while connecting: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by nikhilv85** [tinify/tinify-java#6]
When i try using tinify in android to compress image files,i am getting this error

 Tinify.setKey("xxxxxx"); // xxxx signifies where i place my key 

                    Tinify.validate();

**Comment by rolftimmermans** [comment]
Thanks for reporting this. Would you mind sharing more details about your Android environment? Which versions did you test this on?

**Comment by nikhilv85** [comment]
I tested it on Android studio 2.2.3 and my application is designed for API Level 25

**Comment by nikhilv85** [comment]
More detaile here:

I add the following line to gradle
compile 'com.tinify:tinify:1.4.0'
and add import com.tinify.Tinify; in one of the Android AppActivity
and when i am using 
Tinify.setKey("_xxxxxxx");
byte[] b = Tinify.fromBuffer(b2).toBuffer();
to compress an Image byte array i get the exception
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Is there any update on this?
Is Tinify missing any intermediate security certificates?

**Comment by rolftimmermans** [comment]
Thanks for the information! We have reproduced the issue on Android. It is caused by a subtle incompatibility of the Android implementation of java.security.cert. It is fixed by commit d0b801e9efd388222ff174448f923c93b51824f3.

We have released a new version. Please try **com.tinify:tinify:1.4.1**, and see if this fixes this exception. Thank you! ❤️
