### ISSUE TITLE
Connection leaked

### ISSUE THREAD

**Issue by pgeadas** [tinify/tinify-java#7]
Hello.

While using Tinify, I'm getting the following warning:

Aug 09, 2017 4:11:15 PM com.squareup.okhttp.ConnectionPool pruneAndGetAllocationCount
WARNING: A connection to https://api.tinify.com/ was leaked. Did you forget to close a response body?

I don't find any way of closing the connection in your API. Is there a way to avoid this problem or to close the connection after a request? 

Thank you.

**Comment by simonwahlstrom** [comment]
Hi there!

Would it be possible for you to share your implementation so we can have a look? The connection should automatically be closed so looking at the code would be very helpful!

**Comment by simonwahlstrom** [comment]
Hi again,

Thank you for sharing your implementation and brining this to our attention.

The reason why you are seeing this warning is because you were using a newer version of okhttp. The version that we had specified was 2.5.0 and that version did not have this warning. We have now made a new release (1.5.1) that addresses this issue. 

Please give the new version a try and see if that works better for you. 

Since the new version was just released it might still not be avaliable in Maven, but you could always download the project and give it a go.

**Comment by pgeadas** [comment]
Hi.

I tried out this new version and it exploded, because I was using okhttp 2.7.5.
I will update for the last version and give you feedback after.

Thanks.
